sudo: false
dist: trusty

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

git:
  submodules: false

install:
  - npm install -g codecov
  - npm install

script:
  - npm run test
  - codecov

after_success:
  - npm run doc
  - npm run doc:publish

branches:
  only:
  - master
  - develop
